INFO:root:Start training using device: cuda
INFO:root:Loading the UrbanSED dataset
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/orfeo/cephfs/scratch/dssc/dcapone/YOHO24/yoho/train.py", line 232, in <module>
    for _, file in pd.read_csv(
                   ^^^^^^^^^^^^
  File "/u/dssc/dcapone/scratch/torchenv/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/u/dssc/dcapone/scratch/torchenv/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 620, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/u/dssc/dcapone/scratch/torchenv/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/u/dssc/dcapone/scratch/torchenv/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1880, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
  File "/u/dssc/dcapone/scratch/torchenv/lib/python3.11/site-packages/pandas/io/common.py", line 873, in get_handle
    handle = open(
             ^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/orfeo/cephfs/scratch/dssc/dcapone/YOHO24/yoho/../data/raw/URBAN-SED/train.csv'
/var/spool/slurm/d/job800682/slurm_script: line 19: jupyter: command not found
